[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.normal]
black = "0x393B44"
blue = "0x719CD6"
cyan = "0x64CDCF"
green = "0x81B29A"
magenta = "0x9D79D6"
orange = "0xF4A261"
pink = "0xD67AD2"
red = "0xC94F6D"
white = "0xDFDFE0"
yellow = "0xDBC074"

[colors.primary]
background = "0x192330"
foreground = "0xCDCECF"

[font]
size = 10.0

[font.bold]
family = "Terminess Nerd Font"

[font.italic]
family = "Terminess Nerd Font"

[font.normal]
family = "Terminess Nerd Font"
